---

     - name: Create EC2 server
       ec2:                           
         image: "{{image_name}}"
         wait: yes
         instance_type: "{{instance_type}}"
         region: "{{ region }}"
         group_id: "{{ security_group.group_id }}"
         vpc_subnet_id: "{{ my_public_subnet.subnet.id }}"
         assign_public_ip: yes
         key_name: "{{ssh_key}}"
         count_tag:
            Name: "{{instance_name}}"
            exact_count: 1
